version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
    - "2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  spring-boot-kafka-producer-example:
    image: kafkaproducer:latest
    build: spring-boot-kafka-producer-example/
    network_mode: host
    depends_on:
    - zookeeper
    - kafka
    ports:
    - 8081:8081
    expose:
    - 8081


  spring-boot-kafka-consumer-example:
    image: kafkaconsumer:latest
    build: spring-boot-kafka-consumer-example/
    network_mode: host
    depends_on:
    - zookeeper
    - kafka
    ports:
    - 8082:8082
    expose:
    - 8082


